# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

update_code_signing_settings(
  path: "/Users/aplanetbit/StudioProjects/diccionario_panocho/ios/Runner.xcodeproj",
  use_automatic_signing: true
)

platform :ios do
  desc "Build .ipa file for iOS deployment to App Store"
  lane :buildAdHoc do
        build_app(workspace: "Runner.xcworkspace",
        	scheme: "Runner (Production)",
        	export_method: "app-store",
            	export_options: {
             		provisioningProfiles: {
                		"com.aplanetbit.diccionario.panocho" => "com.aplanetbit.diccionario.panocho AppStore 1558649108",
                		"com.aplanetbit.diccionario.panocho.OneSignalNotificationServiceExtension" => "com.aplanetbit.diccionario.panocho.onesignal"
              		}
            	})
        # sigh(force: true)
        # gym  #  Build with gym - Add actions here: https://docs.fastlane.tools/actions
  end
end
